fix bug2

diff --git a/.github/workflows/merge-check.yml b/.github/workflows/merge-check.yml
--- a/.github/workflows/merge-check.yml
+++ b/.github/workflows/merge-check.yml
@@ -10,21 +10,19 @@ jobs:
     steps:
     - name: Checkout repository content
       uses: actions/checkout@v4
-      with:
-          ref: ${{ github.event.pull_request.head.sha }}
 
     - name: Get all changes in .github/workflows/workflow.yml
-        id: changed-files
-        uses: tj-actions/changed-files@v40
-        with:
-          files: |
-            .github/workflows/workflow.yml
+      id: changed-files
+      uses: tj-actions/changed-files@v4
+      with:
+        files: |
+          .github/workflows/workflow.yml
 
-      - name: Fail if workflow.yml is modified
-        if: steps.changed-files.outputs.any_changed == 'true'
-        run: |
-          echo "Error: .github/workflows/workflow.yml file has been modified in this pull request."
-          exit 1
+    - name: Fail if workflow.yml is modified
+      if: steps.changed-files.outputs.any_changed == 'true'
+      run: |
+        echo "Error: .github/workflows/workflow.yml file has been modified in this pull request."
+        exit 1
     
     - name: Ensure workflow.yml has not been changed
       run: |
